<meta charset="utf-8">
<?php
$variable1 = '123abc';
$variable2 = null;
$variable3 = "";
$variable4 = 'abc123';
$variable5 = 'null';
$var = (int)$variable1;
echo $var . " ";
$var = (float)$variable1;
echo $var . " ";
$var = (string)$variable1;
echo $var . " ";
$var = (boolean)$variable1;
echo $var . " ";
echo "<br>";
$var = (int)$variable2;
echo $var . " ";
$var = (float)$variable2;
echo $var . " ";
$var = (string)$variable2;
echo $var . " ";
$var = (boolean)$variable2;
echo $var . " ";
echo "<br>";
$var = (int)$variable3;
echo $var . " ";
$var = (float)$variable3;
echo $var . " ";
$var = (string)$variable3;
echo $var . " ";
$var = (boolean)$variable3;
echo $var . " ";
echo "<br>";
$var = (int)$variable4;
echo $var . " ";
$var = (float)$variable4;
echo $var . " ";
$var = (string)$variable4;
echo $var . " ";
$var = (boolean)$variable4;
echo $var . "";
echo "<br>";
$var = (int)$variable5;
echo $var . " ";
$var = (float)$variable5;
echo $var . " ";
$var = (string)$variable5;
echo $var . " ";
$var = (boolean)$variable5;
echo $var . "";
echo "<br>Em hiện ra cho biết chứ dự đoán chẳng biết sai đâu mà sửa ạ =))";
?>