CREATE DATABASE IF NOT EXISTS book_oop CHARACTER SET utf8 COLLATE utf8_general_ci;
USE book_oop;
CREATE TABLE book (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL ,
amount INT(11),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)